### ISSUE TITLE
Cannot identify accounts when use 'include'

### ISSUE THREAD

**Issue by MagShadow** [Lencerf/vscode-beancount#29]
+ When splitting the main `.bean` file into several parts and use include to connect them, the extension cannot identify the account correctly so that Wavy Line would appear.

+ For example, in the `main.bean` we have:
```beancount
1970-01-01 open Assets:Wechat
include './2019-09.bean'
```

+ In the `./2019-09.bean`:
```beancount
2019-09-01 balance Assets:Wechat  +10.0 CNY
```

+ The extension cannot identify this 'Assets:Wechat'.

**Comment by Lencerf** [comment]
First you should you double  instead of single quotation marks, see the [language syntax](https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit#), which means:

`include "./2019-09.bean"`

Also have you set `beancount.mainBeanFile` to `main.bean` in workspace settings?

**Comment by MagShadow** [comment]
The quotation mark is just a typo here. In my `bean` file it is correct.

I finished the problem by setting `beancount.mainBeanFile` to `main.bean` in workspace settings. Thank you!

**Comment by Triple-Z** [comment]
> Also have you set `beancount.mainBeanFile` to `main.bean` in workspace settings?

Have the same question, and this tip works. Thx for your reminding.
