### ISSUE TITLE
Provide account completion

### ISSUE THREAD

**Issue by jmgilman** [Lencerf/vscode-beancount#4]
See here for Sublime fix: https://github.com/draug3n/sublime-beancount/issues/5

Basically, in Sublime Text the hack was to modify the word separators setting to exclude the colon. This would effectively treat an account name like an entire word and thus allow fuzzy searching across account names.

VS Code seems to have a similar setting: `editor.wordSeparators`

However, modifying this setting to exclude the colon in my user settings seems to have no effect on word completion. I'm completely unfamiliar with VS Code extensions, is it possible this extension would overwrite that behavior? Is this something that can be implemented within the extension?

**Comment by mariosangiorgio** [comment]
Have a look at the pull request #3. It attempts to solve the issue using a language server.

It's not production ready yet, and it's more complex than just changing the world separator, but it adds completion for both accounts and narrations and it tries to be context aware.

If you decide to try it out and need help let me know. Since you're interested in better completion I'd like to get your feedback.

**Comment by jmgilman** [comment]
Hm, well I see the code where you establish the language server, but I don't see where you're using `bean-query` for auto completion. Also, checking out your complete branch and testing it didn't seem to have any effect. 

Is something missing?

**Comment by jmgilman** [comment]
I just realized the language server is installed independently. Anyways, cloning the changes, npm installing, and debugging the extension within VS code is not providing auto completion (no suggestions after typing : after an account name). 

I'll try to dig into it a little more.

**Comment by mariosangiorgio** [comment]
I'm away for my computer now so I'm afraid I cannot be too helpful. Anyway, before you spend time digging into this issue a few things come to my mind.

For now the path to `bean-query` is hardcoded. Could it be that in your system it's in a different location than mine? This is the first thing I'm planning to add if we decide that we want to integrate the language server in the extensions.

Another possible cause of nothing happening could be that new data is currently loaded only on loading of a new file and on save. If you're starting from an empty file this might be causing your issue.

Finally, for now completion is still very rough. It will only complete the full account, not the individual column separated parts.
Completion uses a very simple heuristic. If the line starts with a digit it assumes that it should fill it in with a narration, otherwise it will suggest an account name.

I hope this will help you figuring out what the issue is.

**Comment by mariosangiorgio** [comment]
One last thing. Completions don't appear automatically (yet). You'll have to trigger them with CTRL+Space (or Command+Space on a Mac)

**Comment by jmgilman** [comment]
Yes, that was it. I don't actually have Beancount installed on the host system, my beancount files are stored in a git repository and I run Beancount through a virtual environment. Temporarily linking the virtual environment bean-query to `/usr/bin/local` started giving me auto completion. 

I agree that hardcoding it isn't ideal, how hard is it to transfer the binary path to an extension configuration file?

**Comment by mariosangiorgio** [comment]
It should be very easy. I might be able to give it a try this evening.

**Comment by dcyoung05** [comment]
I've submitted a PR to modify the word separator as originally proposed.

**Comment by Lencerf** [comment]
The newest release [v0.3.0](https://github.com/Lencerf/vscode-beancount/releases/tag/v0.3.0) supports auto-completion of  account names appeared in all different bean files.
