### ISSUE TITLE
The beancount plugin runs on unrelated files: how to disable this?

### ISSUE THREAD

**Issue by willwray** [Lencerf/vscode-beancount#8]
The extension is running the beancount syntax checking on other files
(that is, besides files with the beancount extension).

How can I configure it, say, to only run on files with beancount extension,
or to not run on particular files?

For instance, it is running on plain text files such as README and on script files.
Then most lines are falsely highlighted as beancount syntax errors.
It is not running on Python files. So, it runs on some file types and not others.

I tried Change Language Mode, but may be missing some simple vscode setting.

It's convenient to use vscode to edit all of the files in the directory.
I'm getting started with beancount, setting up a directory as suggested in the
[Importing External Data](https://docs.google.com/document/d/11EwQdujzEo2cxqaF5PgxCEZXWfKKQCYSMfdJowp_1S8/): document.

**Comment by Lencerf** [comment]
Do you have a main beancount file, which includes all the open/close of accounts? I guess in the document [Importing External Data](https://docs.google.com/document/d/11EwQdujzEo2cxqaF5PgxCEZXWfKKQCYSMfdJowp_1S8/), `personal.beancount` is the main beancount file. If so, you can set `beancount.mainBeanFile` to the path of your main beancount file to solve this problem.

Actually this is bug and I will solve it later so that this extension only checks bean files.

**Comment by willwray** [comment]
Thanks for the quick turn-around fix.
I hit reload on the extension this morning and the red-squiggle-underlines are gone from my non-beancount files*. I'm loving the look of beancount file highlighting, hoping that this will help me continue on my plain-text accounting journey.

Thank you for publishing this extension.

 (*now, just need to banish the pylint squiggles in the python importer code!)
